version: '2'
services:
    postgresql:
      build: 
        context: ./postgresql
        dockerfile: Dockerfile  
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=postgres
      ports:
        - "5432:5432"        
    backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile  
      depends_on:
        - postgresql
      env_file:
        - ./variables.env
      links:
        - "postgresql:postgresql"
      ports:
        - '3000:3000'
      env_file: ./variables.env
    frontend:
      build: 
        context: ./frontend/robbyson
        dockerfile: Dockerfile  
      depends_on:
        - backend
      env_file:
        - ./variables.env
      environment: 
        - 'PORT=3001'
      ports:
        - '3001:3001'